version: '3'

vars:
  git_root:
    sh: git rev-parse --show-toplevel

  default_platforms: linux/amd64,linux/arm64
  base_context: src
  registry: "ghcr.io/soltihq"

tasks:
  default:
    desc: Show usage
    cmds:
      - echo "Please enter a task or use '-l' or '--list-all' to list all available tasks"
    silent: true

# ================================================#
# ---------------------INTERNAL-------------------#
# ================================================#

  _docker/buildx:
    internal: true
    silent: true
    dir: "{{.git_root}}"
    cmds:
      - |
        docker buildx build \
          --platform {{.platforms | default .default_platforms}} \
          --file {{.dockerfile | default (print .base_context "/" .CONTEXT "/" .VERSION "/Dockerfile")}} \
          {{.BUILD_ARGS}} \
          --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
          --label "org.opencontainers.image.source=https://github.com/soltihq/images" \
          --label "org.opencontainers.image.revision=$(git rev-parse HEAD)" \
          --label "org.opencontainers.image.title={{.CONTEXT}}" \
          --label "org.opencontainers.image.version={{.TAG}}" \
          --label "org.opencontainers.image.authors=SoltiHQ" \
          --label "org.opencontainers.image.vendor=Solti" \
          -t {{.registry}}/{{.CONTEXT}}:{{.TAG}} \
          -t {{.registry}}/{{.CONTEXT}}:latest \
          --push \
          {{.context_path | default (print "./" .base_context "/" .CONTEXT "/" .VERSION)}}

# ================================================#
# ---------------------IMAGES---------------------#
# ================================================#

  rust-ci:
    desc: Build 'rust-ci' image.
    silent: true
    vars:
      VERSION: "{{.VERSION}}"
    cmds:
      - task: _docker/buildx
        vars:
          TAG: "{{.VERSION}}"
          CONTEXT: "rust-ci"
          VERSION: "{{.VERSION}}"
