version: '3'

vars:
  git_root:
    sh: git rev-parse --show-toplevel

  default_platforms: linux/amd64,linux/arm64
  base_context: src
  registry: "ghcr.io/soltihq"

tasks:
  default:
    desc: Show usage
    cmds:
      - echo "Please enter a task or use '-l' or '--list-all' to list all available tasks"
    silent: true

# ================================================#
# ---------------------INTERNAL-------------------#
# ================================================#

  _docker/buildx:
    internal: true
    silent: true
    dir: "{{.git_root}}"
    cmds:
      - |
        docker buildx build \
          --platform {{.platforms | default .default_platforms}} \
          --file {{.dockerfile | default (print .base_context "/" .CONTEXT "/" .VERSION "/Dockerfile")}} \
          {{.BUILD_ARGS}} \
          -t {{.registry}}/{{.CONTEXT}}:{{.TAG}} \
          -t {{.registry}}/{{.CONTEXT}}:latest \
          --push \
          {{.context_path | default (print "./" .base_context "/" .CONTEXT "/" .VERSION)}}

# ================================================#
# ---------------------IMAGES---------------------#
# ================================================#

  rust-ci:
    desc: Build 'rust-ci' image.
    silent: true
    vars:
      VERSION: "{{.VERSION}}"
      CARGO_AUDIT_VERSION: "0.22.0"
    cmds:
      - task: _docker/buildx
        vars:
          TAG: "{{.VERSION}}"
          CONTEXT: "rust-ci"
          VERSION: "{{.VERSION}}"
          BUILD_ARGS: >-
            --build-arg CARGO_AUDIT_VERSION={{.CARGO_AUDIT_VERSION}}
            --build-arg RUST_VERSION={{.VERSION}}
